name: QRLock
description: A QR code generator and scanner with encryption

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bubble_bottom_bar: ^1.2.0
  getflutter: ^1.0.11
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  provider: ^5.0.0

  wc_flutter_share: ^0.4.0
  sqflite:
  path:
  flutter_map: any
  latlong: any
  geolocator: ^7.0.3
  map_controller: ^0.9.0
  animated_splash_screen: ^1.1.0
  fluttertoast: ^8.0.7
  url_launcher: ^6.0.4
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.5
  flutter_beep: ^1.0.0
  awesome_dialog: ^2.0.0
  flutter_dialogs: ^1.0.4
  keyboard_visibility: ^0.5.6
  flutter_sms: ^2.3.1
  barcode: ^1.14.0
  path_provider: ^2.0.1
  barcode_widget: ^1.4.0
  barcode_image: ^1.1.0
  country_calling_code_picker: ^1.0.7
  r_scan: ^0.1.4+1
  admob_flutter: ^1.0.1
  image_picker_gallery_camera: ^0.2.2
  share: ^2.0.1
  in_app_purchase: ^0.5.2
dev_dependencies:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
flutter_launcher_name:
  name: "QR Privacy"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/tabs/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: EBGaramond
     fonts:
       - asset: fonts/EBGaramond-Regular.ttf
       - asset: fonts/EBGaramond-Italic.ttf
       - asset: fonts/EBGaramond-Bold.ttf
       - asset: fonts/EBGaramond-SemiBold.ttf
uses-material-design: true
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
